allowBuilds:
  "@swc/core": true
  electron: true
  electron-winstaller: true
  esbuild: true
blockExoticSubdeps: false
minimumReleaseAgeExclude:
  - app-builder-lib@26.15.6
  - dmg-builder@26.15.6
  - electron-builder-squirrel-windows@26.15.6
  - electron-forge-maker-appimage@26.15.6
nodeLinker: hoisted
onlyBuiltDependencies:
  - "@swc/core"
  - electron
  - electron-winstaller
  - esbuild
patchedDependencies:
  electron-installer-redhat: patches/electron-installer-redhat.patch
